### ISSUE TITLE
Github auth broken on GHA

### ISSUE THREAD

**Issue by assignUser** [ropenscilabs/allcontributors#23]
https://github.com/ropensci-review-tools/pkgcheck-action/runs/4952551944?check_suite_focus=true#step:5:11

It seems to be an issue with {gitcreds}

**Comment by mpadge** [comment]
That's okay; it's not really meant to be run completely automatically. I think that those lists should always be manually checked before committing, primarily because the do contain directly personal details that we should presume always need checking, so could just remove that call from the workflow.

**Comment by assignUser** [comment]
That makes sense.
