### ISSUE TITLE
make "link check" more specific to GitHub?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/allcontributors#45]
why not send a call to the users REST endpoint and see whether a 404 is returned?

**Comment by mpadge** [comment]
That is what is done, although just to main page:
https://github.com/ropenscilabs/allcontributors/blob/cc624093840810f2ab6d68a0173c6cfd7722187e/R/urlcheck.R#L13

doesn't make any difference though. The problem was that code was only accepting `status = 429`, but the whole thing runs in a curl pool request
https://github.com/ropenscilabs/allcontributors/blob/cc624093840810f2ab6d68a0173c6cfd7722187e/R/urlcheck.R#L63
and that often returns 429. Above commit just replaced `out == 200` with `out != 404`. Thanks again

**Comment by maelle** [comment]
@mpadge why not use gh for that call so that not too many requests are sent at once then?

**Comment by mpadge** [comment]
Because I did try that back at the time, and using a curl pool was literally thousands of times faster. The `check_url = TRUE` option via `gh` becomes so slow that it's unusable. I think the good aspect there is that, at least in my test from your igraph example, the 400's were caught. 429's don't matter as long as they don't mask 400's, which I'm happy to presume for now is indeed the case.
